Mark Phonon as a required module in CMake
Summary:
Right now, Blinken does not require Phonon in CMake:

```
-- The following OPTIONAL packages have not been found:

 * Phonon4Qt5

-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/packages/user/blinken/src/blinken-17.12.2
```

However, this results in a build failure:

```
[ 76%] Building CXX object src/CMakeFiles/blinken.dir/main.cpp.o
In file included from /usr/src/packages/user/blinken/src/blinken-17.12.2/src/soundsplayer.cpp:10:0:
/usr/src/packages/user/blinken/src/blinken-17.12.2/src/soundsplayer.h:13:30: fatal error: phonon/MediaObject: No such file or directory
 #include <phonon/MediaObject>
                              ^
compilation terminated.
make[2]: *** [src/CMakeFiles/blinken.dir/build.make:119: src/CMakeFiles/blinken.dir/soundsplayer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 76%] Built target doc-index-cache-bz2
In file included from /usr/src/packages/user/blinken/src/blinken-17.12.2/src/blinkengame.cpp:17:0:
/usr/src/packages/user/blinken/src/blinken-17.12.2/src/soundsplayer.h:13:30: fatal error: phonon/MediaObject: No such file or directory
 #include <phonon/MediaObject>
                              ^
compilation terminated.
make[2]: *** [src/CMakeFiles/blinken.dir/build.make:143: src/CMakeFiles/blinken.dir/blinkengame.cpp.o] Error 1
```

This patch forces Phonon to be required.

Test Plan: Tested on git master and 17.12.2 release tarballs on Linux.  Since this is an unconditional header I cannot see this requiring testing on other platforms; the behaviour should be the same.

Reviewers: aacid

Subscribers: kde-edu, #kde_edu

Tags: #kde_edu

Differential Revision: https://phabricator.kde.org/D11700